### PR TITLE
comment out halftone check

### LINKED ISSUE #878: BitmapConverter ToMat() NotImplementedException("Not supported halftone Palette");
# Summary of your issue
I'm using a pair of monochrome cameras which acquire images in Bitmap format. For further image processing using OpenCVSharp, the images need to be converted to Mat format. Previous version (4.0.0.20181129) had no issues doing the conversion. The latest version (4.2.0.20200208) throws the exception "NotImplementedException("Not supported halftone Palette");". The images used as input haven't changed at all. 

# Environment
Windows 10
Visual Studio 2019
OpenCVSharp version (4.2.0.20200208) - downloaded from the NuGet Package Manager
Framework: .Net Framework 4.6.1

# What did you do when you faced the problem?
1. Tried to implement the ToMat() method without handling the Bitmap.Palette.Flag
Outcome: More errors arose

2. Tried to change the Bitmap palette from halftone to grayscale. It's not possible.

## Example code:

camera.Memory.ToBitmap(memoryID, out BitmapI); // IDS Camera library method
Mat matImage = new Mat();
BitmapConverter.ToMat(BitmapI, matImage);

### PR DESCRIPTION
**Pull request by shimat**
Fix #878

### CODE REVIEW

File: src/OpenCvSharp.Extensions/BitmapConverter.cs [hunk 1]
```diff
@@ -156,8 +155,8 @@ public static unsafe void ToMat(this Bitmap src, Mat dst)
                             throw new ArgumentException("Invalid nChannels");
                         if (dst.Depth() != MatType.CV_8U && dst.Depth() != MatType.CV_8S)
                             throw new ArgumentException("Invalid depth of dst Mat");
-                        if (src.Palette.Flags == 4) // https://docs.microsoft.com/ja-jp/dotnet/api/system.drawing.imaging.colorpalette.flags?view=netframework-4.8
-                            throw new NotImplementedException("Not supported halftone Palette");
+                        //if (src.Palette.Flags == 4) // https://docs.microsoft.com/ja-jp/dotnet/api/system.drawing.imaging.colorpalette.flags?view=netframework-4.8
+                        //    throw new NotImplementedException("Not supported halftone Palette");
```
Comment (kanstantsin) [inline src/OpenCvSharp.Extensions/BitmapConverter.cs]: I assume that this check is guarding against trying to use any bitmap except of grayscale (as only red component is used from palette), right? Maybe there is another way to make sure that the bitmap is grayscale to still be able to throw on unexpected input? For example, check that all colors in palette have same R, G and B value. But I'm not sure how it will impact conversion performance.
Or maybe number of channels check on line 154 already prevents incorrect usage.

Comment (shimat) [reply src/OpenCvSharp.Extensions/BitmapConverter.cs]: Thank you for your comment. This code block is for Bitmap.PixelFormat==8bppIndexed. I understand 8bppIndexed to mean grayscale. So if the values of each of the palette's R, G, and B are different, I'm not sure how to handle that.
```c#
// pseudo-code
byte[] bitmapValues = ... ;
var palette = bitmap.Palette;

byte[] matValues = bitmapValues.Select(b => {
    byte newR = palette.Entries[b].R;
    byte newG = palette.Entries[b].G;
    byte newB = palette.Entries[b].B;
    return ???; // What should I merge RGB into one byte value?
}).ToArray();
```

In the EmguCV implementation, it looks like that the method returns a 8UC3 (Color) Mat, even though the input Bitmap is 8bppIndexed. That makes me wonder a little bit, but maybe I should go with that.

Comment (kanstantsin) [reply src/OpenCvSharp.Extensions/BitmapConverter.cs]: I did some more research and here's what I got.
`8bppIndexed` is in fact not defined as grayscale format, it just defines that there are 256 colors in palette, which consists of any colors. [Here ](https://gist.github.com/kanstantsin/b5518b2505f5f3dd3d08cfc85826ef52)is the code which generates 64x64 green and red bitmap with `8bppIndexed` format. One more interesting thing is that `Palette.Flags` contains value `4` regardless of palette contents which is created automatically (you can't create palette manually or change its flags). At least I didn't find a way to create `8bppIndexed` image with other values in flags. Perhaps it is possible when bitmap is loaded from file.
What I think about it is probably we can check destination `Mat` type and act depending on number of channels in it. As a simple solution maybe we can stay with current version of merge request (although I prefer removing code instead of commenting it out in production code), but keep in mind that current version of code does not cover colored `8bppIndexed` images.

Comment (shimat) [reply src/OpenCvSharp.Extensions/BitmapConverter.cs]: Thank you for the useful information. I made a branch of the process by type of dst.
